### ISSUE TITLE
Suggestion: Tidy5eSheet support

### ISSUE THREAD

**Issue by ravingdragoon** [kandashi/spellbook-assistant-manager#5]
It would be really cool if this could work with Tidy5eSheet. Perhaps adding the column and then just inputting the text of the source class, rather than the bulkier icon, in order to stay within the format of that sheet. I will also raise this with the Tidy5eSheet module in case it can/must be worked from their side.

**Comment by DivertedCircle** [comment]
As part of this, there's a display issue that would also need to be addressed when using this module in tandem with Tidy5e Sheet.
https://github.com/sdenec/tidy5e-sheet/issues/441

**Comment by kandashi** [comment]
added compatibility
